name: custom_notification_scheduler_example
description: A Flutter plugin for scheduling notifications with custom sounds and FCM support. on Android and iOS.
homepage: https://zihadsikder.vercel.app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  custom_notification_scheduler:
    path: /Users/zihad/Desktop/untitled folder/custom_notification_scheduler
  permission_handler:
  flutter_local_notifications:
  timezone:
  plugin_platform_interface:
  cupertino_icons:

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito:


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

