name: custom_notification_scheduler
description: A Flutter plugin for scheduling notifications with custom sounds and FCM support. on Android and iOS.
version: 0.0.5
homepage: https://github.com/zihadsikder/custom_notification_scheduler

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_local_notifications: ^19.2.1
  flutter_local_notifications_platform_interface: ^9.0.0
  timezone: ^0.10.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/sounds/custom_sound.mp3
    # - assets/latest_all.tzf
  plugin:
    platforms:
      android:
        package: app.vercel.zihadsikder.custom_notification_scheduler
        pluginClass: CustomNotificationSchedulerPlugin
      ios:
        pluginClass: CustomNotificationSchedulerPlugin

