name: custom_notification_scheduler
description: A Flutter plugin for scheduling notifications with custom sounds and FCM support. on Android and iOS.
version: 0.0.2
homepage: https://github.com/zihadsikder/custom_notification_scheduler

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
  flutter_local_notifications:
  flutter_local_notifications_platform_interface:
  timezone:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/sounds/custom_sound.mp3
  plugin:
    platforms:
      android:
        package: app.vercel.zihadsikder.custom_notification_scheduler
        pluginClass: CustomNotificationSchedulerPlugin
      ios:
        pluginClass: CustomNotificationSchedulerPlugin

