name: custom_notification_scheduler
description: A plugin to schedule custom local notifications on Android and iOS.
version: 0.0.1
homepage: https://github.com/zihadsikder/custom_notification_scheduler

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.vercel.zihadsikder.custom_notification_scheduler
        pluginClass: CustomNotificationSchedulerPlugin
      ios:
        pluginClass: CustomNotificationSchedulerPlugin

